# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-17 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_auto_20191017_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photo',
            new_name='profile_photo',
        ),
        migrations.AddField(
            model_name='image',
            name='profile_photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instagram.Profile'),
        ),
    ]
